### PR TITLE
More edits to index, README

### PR DESCRIPTION
**Pull request by skinn009**
Alerted users that nltk must be installed.  My list of needed packages may be incomplete, ambiguous, or redundant.

### CODE REVIEW

**Review by hayesall — CHANGES_REQUESTED** [review]
Maybe a code block showing how to install the dependencies?

I pulled these out of the top of the current `setup.py`, having them in a similar format to this might make it a little more clear.

```python
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
```

**Comment by hayesall** [comment]
@leodd is working on getting an `install_requires` keywords in the setup file to simplify this a bit further, but having the explicit instructions as part of the documentation would be good to have.

```
.. code-block:: python

  import nltk
  nltk.download('punkt')
  nltk.download('stopwords')
  nltk.download('averaged_perceptron_tagger')
```

**Comment by skinn009** [comment]
Will do.

**Review by hayesall — APPROVED** [review]

**Comment by hayesall** [comment]
These look good, I'm going to squash-and-merge since there were a few incremental changes. Thanks Mike!

**Comment by skinn009** [comment]
Alex, I made the changes you requested on my remote.  Do we just do another
pull request, or do we abort the pending pull?

Mike

**Comment by skinn009** [comment]
Oh- our messages passed in the mail.

On Fri, Aug 3, 2018 at 1:01 PM, Alexander L. Hayes <notifications@github.com

**Comment by hayesall** [comment]
@skinn009 Adding the additional commits on the same branch as the pull request are also added to be part of the pull request, so all of your changes were merged in herer. I did a "squash merge" on this though since there were a few incremental changes to the same lines of the same files.

**Comment by skinn009** [comment]
I may not be understanding your changes- what if the user decides she
doesn't want nltk installed, and would rather not use rnlp if the package
is required?  I wonder if most users would rather control any package
imports.

On Fri, Aug 3, 2018 at 1:17 PM, Alexander L. Hayes <notifications@github.com

**Pull request merged**
