### PR TITLE
Small changes to index, .gitignore

### PR DESCRIPTION
**Pull request by skinn009**
Added pycharm environment control files to .gitignore.

### CODE REVIEW

**Review by hayesall — APPROVED** [review]
These look good, should be fine to merge into master.

**Comment by skinn009** [comment]
Can I do that?

**Comment by hayesall** [comment]
@skinn009 Yep. You should have a "Merge pull request" option now that the changes are approved, if it isn't appearing let me know (I was tweaking some access options when adding you and Yuqiao, but if it isn't appearing I should be able to fix it).

**Comment by skinn009** [comment]
Edits to documentation.

**Comment by skinn009** [comment]
Okay- I think I merged.  Thanks.

Mike

**Pull request merged**
