### PR TITLE
Setup File Corrections

### PR DESCRIPTION
**Pull request by hayesall**
This PR:

* Bumps the version number from 0.3.1 to 0.3.2
* Overwrites the `setup.py` install method in order to also download `nltk` package requirements.

### CODE REVIEW

**Review by leodd — APPROVED** [review]

**Comment by skinn009** [comment]
Is this where I should comment on your code changes?- mas

**Comment by skinn009** [comment]
what if the user decides she doesn't want nltk installed, and would rather not use rnlp if the package is required?  I wonder if most users would rather control any package imports.

**Comment by hayesall** [comment]
> what if the user decides she doesn't want nltk installed, and would rather not use rnlp if the package is required? I wonder if most users would rather control any package imports

I think this is a good point, but we have two somewhat mutually exclusive options:

1. The package is easy to install (and handles installing all dependencies)
2. The package is harder to install but checks everything with the user

A good middle ground (in my opinion) would be to list the dependencies (such that a user can inspect them ahead of time), but make the package easy to install.

**Comment by skinn009** [comment]
I wonder if there is another option: the user installs the necessary packages (according to the code instructions we gave in the README).  Then it is a simple matter to install rnlp.  I guess we need to balance ease of use with user sovereignty, and I of course will defer to your expertise and experience.

**Comment by hayesall** [comment]
> the user installs the necessary packages (according to the code instructions we gave in the README).

This is basically the same as (2), but manually installing everything gets messy the further down you go. For example, [Sphinx](https://github.com/sphinx-doc/sphinx/network/dependencies) requires 12 Python dependencies to be fulfilled (each of which may also have their own dependencies).

`setup.py` helps manage dependencies and gets someone to the point where they can use the software with (hopefully) the minimal number of packages.

Manually installing specific packages (like `sphinx`, or `unittest`) makes sense--since not everyone will be building the documentation from scratch or running unit tests. Other packages (such as `nltk`) are absolutely required because a person cannot use this software without either rewriting the code or installing `nltk`.

**Comment by skinn009** [comment]
Okay.  Thanks for schooling me!

**Pull request merged**
